### ISSUE TITLE
Schedule Error

### ISSUE THREAD

**Issue by sscotth** [byalextran/autoluv#1]
```
$ ./bin/autoluv schedule -c ABC123 -f First -l Last -e "email+autoluv@example.com" --trace

/home/scott/code/autoluv/vendor/bundle/ruby/2.3.0/gems/commander-4.3.5/lib/commander/user_interaction.rb:334: warning: constant ::TimeoutError is deprecated
/home/scott/code/autoluv/lib/autoluv/flight.rb:19:in `initialize': undefined method `[]' for nil:NilClass (NoMethodError)
	from /home/scott/code/autoluv/lib/autoluv/southwest.rb:50:in `new'
	from /home/scott/code/autoluv/lib/autoluv/southwest.rb:50:in `departing_flights'
	from ./bin/autoluv:100:in `block (2 levels) in <main>'
	from /home/scott/code/autoluv/vendor/bundle/ruby/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /home/scott/code/autoluv/vendor/bundle/ruby/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /home/scott/code/autoluv/vendor/bundle/ruby/2.3.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /home/scott/code/autoluv/vendor/bundle/ruby/2.3.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /home/scott/code/autoluv/vendor/bundle/ruby/2.3.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /home/scott/code/autoluv/vendor/bundle/ruby/2.3.0/gems/commander-4.3.5/lib/commander/import.rb:5:in `block in <top (required)>'
```

**Comment by byalextran** [comment]
heya @sscotth. on your departing flight, what city or cities are you flying into (including layovers)? if it's a round trip flight, same question for your returning flight as well.

**Comment by sscotth** [comment]
BNA and FLL

**Comment by byalextran** [comment]
aha, just as i suspected! i was doing some pretty strict checking on the airport city which didn't allow for periods in the city name (like ft. lauderdale). 

i've pushed an updated version which is a lot less strict on the airport city. grab that version and let me know if your flight schedules properly.

**Comment by sscotth** [comment]
I had to `sudo apt-get install at` but it seems to have scheduled. I'll let you know if it completes.
