### ISSUE TITLE
NameError in 'validate'

### ISSUE THREAD

**Issue by atorg** [byalextran/autoluv#3]
Looks like a cool script but I'm getting an error.
Here's the trace:

```
./bin/autoluv schedule -c ABC123 -f First -l Last -e "example@notarealemail.com" --trace
/home/at/autoluv/lib/autoluv/southwest.rb:156:in `validate': undefined local variable or method `__dir__' for #<AutoLUV::Southwest:0x00000001a17e70> (NameError)
	from /home/at/autoluv/lib/autoluv/southwest.rb:39:in `departing_flights'
	from ./bin/autoluv:100:in `block (2 levels) in <main>'
	from /home/at/autoluv/vendor/bundle/ruby/1.9.1/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /home/at/autoluv/vendor/bundle/ruby/1.9.1/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /home/at/autoluv/vendor/bundle/ruby/1.9.1/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /home/at/autoluv/vendor/bundle/ruby/1.9.1/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /home/at/autoluv/vendor/bundle/ruby/1.9.1/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /home/at/autoluv/vendor/bundle/ruby/1.9.1/gems/commander-4.3.5/lib/commander/delegates.rb:19:in `run!'
	from /home/at/autoluv/vendor/bundle/ruby/1.9.1/gems/commander-4.3.5/lib/commander/import.rb:5:in `block in <top (required)>'
```

**Comment by byalextran** [comment]
i believe the problem is because `__dir__` was introduced in ruby 2.0. i bet if you upgrade your ruby version to the latest, the problem will be fixed.

**Comment by atorg** [comment]
Thanks--updated my Ruby version to 2.0.0, and that error disappeared. However now I'm getting the following one. Am I missing some dependency?

```
./bin/autoluv schedule -c ABC123 -f First -l Last -e "example@notarealemail.com" --trace
/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require': cannot load such file -- bundler/setup (LoadError)
	from /usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'
	from ./bin/autoluv:3:in `<main>'
```

**Comment by byalextran** [comment]
yup, you're missing the bundler gem for your new version of ruby. 

`gem install bundler`

run that and then try it again.

**Comment by atorg** [comment]
Tried that, and then cloned and ran 
```
bundle install --deployment
```
again but still getting
```
./bin/autoluv schedule -c ABC123 -f First -l Last -e "example@notarealemail.com" --trace
/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require': cannot load such file -- bundler/setup (LoadError)
	from /usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'
	from ./bin/autoluv:3:in `<main>'
```
which looks like the same error. Other thoughts?

**Comment by atorg** [comment]
My Ruby installation was all sorts of messed up. I reinstalled everything cleanly and now the script works well. Thanks!

**Comment by byalextran** [comment]
great, glad you got it working! if you're not familiar with [chruby](https://github.com/postmodern/chruby) and [ruby-install](https://github.com/postmodern/ruby-install), i would highly recommend you use them to manage your ruby versions.
