### ISSUE TITLE
Error message when trying to run

### ISSUE THREAD

**Issue by KnightTim** [byalextran/autoluv#6]
```
$ ./bin/autoluv schedule --help
/home/tim/autoluv/vendor/bundle/ruby/2.1.0/gems/commander-4.4.1/lib/commander/runner.rb:407:in `block in require_program': program version required (Commander::Runner::CommandError)
        from /home/tim/autoluv/vendor/bundle/ruby/2.1.0/gems/commander-4.4.1/lib/commander/runner.rb:406:in `each'
        from /home/tim/autoluv/vendor/bundle/ruby/2.1.0/gems/commander-4.4.1/lib/commander/runner.rb:406:in `require_program'
        from /home/tim/autoluv/vendor/bundle/ruby/2.1.0/gems/commander-4.4.1/lib/commander/runner.rb:52:in `run!'
        from /home/tim/autoluv/vendor/bundle/ruby/2.1.0/gems/commander-4.4.1/lib/commander/delegates.rb:15:in `run!'
        from /home/tim/autoluv/vendor/bundle/ruby/2.1.0/gems/commander-4.4.1/lib/commander/import.rb:5:in `block in <top (required)>'
./bin/autoluv:7:in `require': /home/tim/autoluv/vendor/bundle/ruby/2.1.0/gems/luvwrapper-0.3.3/lib/luvwrapper.rb:19: syntax error, unexpected ':', expecting => (SyntaxError)
    "X-API-Key": "l7xx12ebcbc825eb480faa276e7f192d98d1",
                ^
/home/tim/autoluv/vendor/bundle/ruby/2.1.0/gems/luvwrapper-0.3.3/lib/luvwrapper.rb:19: syntax error, unexpected ',', expecting keyword_end
/home/tim/autoluv/vendor/bundle/ruby/2.1.0/gems/luvwrapper-0.3.3/lib/luvwrapper.rb:27: syntax error, unexpected ':', expecting =>
        "first-name": first_name,
                     ^
/home/tim/autoluv/vendor/bundle/ruby/2.1.0/gems/luvwrapper-0.3.3/lib/luvwrapper.rb:28: syntax error, unexpected ':', expecting :: or '[' or '.'
        "last-name": last_name,
                    ^
/home/tim/autoluv/vendor/bundle/ruby/2.1.0/gems/luvwrapper-0.3.3/lib/luvwrapper.rb:29: syntax error, unexpected ':', expecting :: or '[' or '.'
        "action": "VIEW"
                 ^
/home/tim/autoluv/vendor/bundle/ruby/2.1.0/gems/luvwrapper-0.3.3/lib/luvwrapper.rb:30: syntax error, unexpected '}', expecting keyword_end
/home/tim/autoluv/vendor/bundle/ruby/2.1.0/gems/luvwrapper-0.3.3/lib/luvwrapper.rb:82: syntax error, unexpected ':', expecting =>
      "Content-Type": "application/vnd.swacorp.com...
                     ^
/home/tim/autoluv/vendor/bundle/ruby/2.1.0/gems/luvwrapper-0.3.3/lib/luvwrapper.rb:83: syntax error, unexpected '}', expecting keyword_end
    }.merge(DEFAULT_OPTIONS)
     ^
/home/tim/autoluv/vendor/bundle/ruby/2.1.0/gems/luvwrapper-0.3.3/lib/luvwrapper.rb:152: syntax error, unexpected ':', expecting =>
      "Content-Type": "application/vnd.swacorp.com...
                     ^
/home/tim/autoluv/vendor/bundle/ruby/2.1.0/gems/luvwrapper-0.3.3/lib/luvwrapper.rb:153: syntax error, unexpected '}', expecting keyword_end
    }.merge(DEFAULT_OPTIONS)
     ^
        from ./bin/autoluv:7:in `<main>'
```

**I'm not sure what is causing this when I try to do anything.**

**Comment by byalextran** [comment]
on cursory glance, i think the issue is that your ruby version (2.1) doesn't support the hash syntax i'm using. if you upgrade your ruby version to 2.2 or above and reinstall, i think things should work. 

i incorrectly specified 2.0 as the minimum version. i'll have to update that. thanks for the heads up!
